version: '3'
services:
  moodle_prod:
    image: docker.io/bitnami/moodle:4.2.2
    container_name: moodle
    hostname: moodle
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_SKIP_BOOTSTRAP=yes
      - MOODLE_DATABASE_HOST=
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=
      - MOODLE_DATABASE_NAME=
      - MOODLE_DATABASE_PASSWORD=
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
volumes:
  moodle_data:
  moodledata_data:
